apiVersion: v1
kind: Secret
metadata:
  name: hgdb-app
type: kubernetes.io/basic-auth
data:
  username: [BASE64_ENCODED_USERNAME]
  password: [BASE64_ENCODED_PASSWORD]
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-creds
data:
  ACCESS_KEY_ID: [BASE64_ENCODED_ACCESS_KEY_ID]
  ACCESS_SECRET_KEY: [BASE64_ENCODED_ACCESS_SECRET_KEY]
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: recovered-hgdb
spec:
  description: "Health Gateway recovered Database"
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  instances: 1

  superuserSecret:
    name: superuser-secret

  bootstrap:
    recovery:
      source: hgdb
      database: hglocal
      owner: hglocal
      secret:
        name: hgdb-app

 
  storage:
    storageClass: standard
    size: 5Gi

  externalClusters:
    - name: hgdb
      barmanObjectStore:
        destinationPath: s3://[BUCKET_NAME]
        endpointURL: [ENDPOINT_URL]
        s3Credentials:
          accessKeyId:
            name: backup-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: backup-creds
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8